### ISSUE TITLE
SoC wird nicht gespeichert, womöglich timeout

### ISSUE THREAD

**Issue by MartinRinas** [openWB/core#1075]
Tesla SoC wird zuverlässig abgerufen und taucht im Log auf, allerdings fehlt die letzte Meldung zum speichern des CarState wenn das Auto zuerst aufgeweckt werden muss.
Ist das Auto vor dem Abruf wach wird alles gespeichert.

https://github.com/openWB/core/pull/1029#issue-1799855544

SoC wird gespeichert:
2023-07-07 11:14:03,795 - {modules.common.store._api:26} - {DEBUG:soc_ev3} - Raw data CarState(soc=77.0, range=373.8335886, soc_timestamp=)
2023-07-07 11:14:03,818 - {modules.common.store._api:30} - {INFO:soc_ev3} - Saving CarState(soc=77.0, range=373.8335886, soc_timestamp=)

SoC wird nicht gespeichert:
2023-07-07 11:11:27,002 - {modules.common.store._api:26} - {DEBUG:soc_ev3} - Raw data CarState(soc=77.0, range=373.8335886, soc_timestamp=)

**Comment by Flock82** [comment]
Gleiches Problem bei Kia. Kann der SoC nicht innerhalb einiger Sekunden (evtl. vor der nächsten Regelschleife?) bereitgestellt werden, wird er nicht gespeichert.

**Comment by LKuemmel** [comment]
Bitte mit dem Feature-Branch feature_timeout_soc testen. Vor dem Branchwechsel eine Sicherung erstellen.

**Comment by MartinRinas** [comment]
jup, teste ich gleich mal.

**Comment by Flock82** [comment]
Funktioniert bei mir auch mit den Änderungen

**Comment by Flock82** [comment]
Leider hat der Fix eine unschöne Nebenwirkung, die mir erst jetzt aufgefallen ist: Während das SoC-Modul läuft, werden die Weete von den anderen Modulen(in meinem Fall alle MQTT) nicht mehr übernommen, was unschöne Lücken im Graphen erzeugt.

**Comment by benderl** [comment]
Die Anpassung ist im master. Bitte einmal testen.

**Comment by Flock82** [comment]
Läuft jetzt gut bei mir.

**Comment by benderl** [comment]
Dann schließe ich mal.
