### ISSUE TITLE
tests für counter_test.py schlagen in VSCode fehl?

### ISSUE THREAD

**Issue by MartinRinas** [openWB/core#1184]
Mir ist eben aufgefallen dass einige tests in counter_test.py bei mir in VSCode fehlschlagen, hat jemand eine Idee woran das liegen kann? 
Die automatiserten Tests in den PRs laufen ja durch, kann also kein Problem mit dem Code sein. bin auf dem aktuellen Master (c4a0d320).

![image](https://github.com/openWB/core/assets/29856849/154149dd-53b3-42e4-84c2-1b19b32a2416)

`/var/www/html/openWB/packages/control/counter_test.py::test_switch_on_threshold_reached[Einschaltschwelle wurde unterschritten, Timer zur\xfccksetzen] failed: params = Params(name='Einschaltschwelle wurde unterschritten, Timer zurücksetzen', feed_in_limit=False, reserved_surplus=1500, ... während der Einschaltverzögerung unterschritten.', expected_timestamp_switch_on_off=None, expected_reserved_surplus=0)
caplog = <_pytest.logging.LogCaptureFixture object at 0x7fab10fb8b50>
general_data_fixture = None
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fab1101bb80>

    @pytest.mark.parametrize("params", cases, ids=[c.name for c in cases])
    def test_switch_on_threshold_reached(params: Params, caplog, general_data_fixture, monkeypatch):
        # setup
        c = Counter(0)
        c.data.set.reserved_surplus = params.reserved_surplus
        cp = Chargepoint(0, None)
        ev = Ev(0)
        cp.data.control_parameter.phases = 1
        cp.data.control_parameter.state = params.state
        cp.data.control_parameter.timestamp_switch_on_off = params.timestamp_switch_on_off
        ev.data.charge_template = ChargeTemplate(0)
        ev.data.charge_template.data.chargemode.pv_charging.feed_in_limit = params.feed_in_limit
        cp.data.set.charging_ev_data = ev
        mock_calc_switch_on_power = Mock(return_value=[params.surplus, params.threshold])
        monkeypatch.setattr(Counter, "calc_switch_on_power", mock_calc_switch_on_power)
    
        # execution
        c.switch_on_threshold_reached(cp)
    
        # evaluation
        assert c.data.set.reserved_surplus == params.expected_reserved_surplus
>       assert params.expected_msg is None or params.expected_msg in caplog.text
E       AssertionError: assert ('Einschaltschwelle während der Einschaltverzögerung unterschritten.' is None or 'Einschaltschwelle während der Einschaltverzögerung unterschritten.' in '')
E        +  where 'Einschaltschwelle während der Einschaltverzögerung unterschritten.' = Params(name='Einschaltschwelle wurde unterschritten, Timer zurücksetzen', feed_in_limit=False, reserved_surplus=1500, ... während der Einschaltverzögerung unterschritten.', expected_timestamp_switch_on_off=None, expected_reserved_surplus=0).expected_msg
E        +  and   'Einschaltschwelle während der Einschaltverzögerung unterschritten.' = Params(name='Einschaltschwelle wurde unterschritten, Timer zurücksetzen', feed_in_limit=False, reserved_surplus=1500, ... während der Einschaltverzögerung unterschritten.', expected_timestamp_switch_on_off=None, expected_reserved_surplus=0).expected_msg
E        +  and   '' = <_pytest.logging.LogCaptureFixture object at 0x7fab10fb8b50>.text

packages/control/counter_test.py:146: AssertionError`

**Comment by benderl** [comment]
Ist bei mir auch so. Die Prüfung der Infomeldung schlägt fehl, da die anscheinend immer `None` ist. Bei den erfolgreichen Tests wird auch `None` erwartet.
