### ISSUE TITLE
SMB Backup: Dateien werde nicht abgelegt

### ISSUE THREAD

**Issue by Saharel001** [openWB/core#1186]
Hallo zusammen, dass samba Modul scheint noch nicht so ganz zu funktionieren.
Ich habe einen Share auf einen QNAP angegeben, User, Passwort. Leider bleibt das Share leer.

Probiert habe ich: 
//IP/Share/Folder
//IP/Share
\\\IP\Share\Folder
\\\IP\Share

Leider fehlt hier ein Wikieintrag zu.

Auf der openwb unter http://IP/openWB/data/backup/ wird immer eine frische Datei erzeugt.
Da das Modul wenig bis keine Logs ausspuckt bis auf das eine, kann ich es nur beschreiben.
`SMB.SMBConnection:104} - {INFO:cloud backup} - Authentication with remote machine "SERVER" for user "xxx" will be using NTLM v2 authentication (with extended security)`
Hier verwundert mich der Name meiner "remote maschine". Wurde hier eventuell die IP ignoriert.
QNAP protokoliert keinerlei Verbindungsversuche von meiner openwb

Die Verbindung via Explorer ist kein Problem, Schreibrechte hat der User auch:
![image](https://github.com/openWB/core/assets/24453343/fd984bff-e73c-4fbe-b990-13d1d96aa2d2)

**Comment by Saharel001** [comment]
Ich habe den Fehler gefunden, in der Initialisierung der SMB Verbindung ist der Name 'server' hard gecoded ;) Außerdem wurde nicht nach https://pysmb.readthedocs.io/en/latest/api/smb_SMBConnection.html gearbeitet.

Werde es beheben und nen PR stellen.

**Comment by Saharel001** [comment]
PR steht: https://github.com/openWB/core/pull/1187

**Comment by Saharel001** [comment]
durch PR erledigt

**Comment by Sleepwalker86** [comment]
Danke für deine Korrektur, das war mein erster Versuch mit ein wenig Hilfe von ChatGPT. :-D Bin leider kein Programmierer. Vielen Dank nochmal für die Korrektur.
Gruß Sascha
