### ISSUE TITLE
Status View

### ISSUE THREAD

**Issue by Saharel001** [openWB/core#1215]
Ist kein Bug nur ein Vorschlag. 
Um das Display Thema konsistent zu halten, wäre es gut die Statusview auch in eine dash-board-card zu packen.
Würde dann so aussehen:
![image](https://github.com/openWB/core/assets/24453343/2c772956-44eb-49b9-b92e-134e8882bd4a)

Außerdem würde ich gerne die Ladepunkte wie folgt anpassen:
![image](https://github.com/openWB/core/assets/24453343/8e84b1ff-0f8d-45d5-954c-b7555985ffab)

@benderl  @LKuemmel @MartinRinas 
Was haltet ihr davon?

**Comment by MartinRinas** [comment]
einheitliches Look&Feel finde ich immer gut! 
Kann man bei der Statusseite das Label und den Wert in die gleiche Zeile packen? also

IP-Adresse: <Wert>
anstelle

IP-Adresse:
<Wert>

Wirkt m.E. dann aufgeräumter und der vorhandene Platz wird besser genutzt.

**Comment by Saharel001** [comment]
> einheitliches Look&Feel finde ich immer gut! Kann man bei der Statusseite das Label und den Wert in die gleiche Zeile packen? also
> 
> IP-Adresse: 192.168.178.57 anstelle
> 
> IP-Adresse: 192.168.178.57
> 
> Wirkt m.E. dann aufgeräumter und der vorhandene Platz wird besser genutzt.

Du meinst so?
![image](https://github.com/openWB/core/assets/24453343/6e6ac646-2e4d-48cb-a871-ed28107faf75)

**Comment by MartinRinas** [comment]
ja, da finde ich persönlich schon deutlich besser. Vielleicht die Boxen noch etwas breiter machen damit die nach links rutschen, dann passt auch die Versionsnummer komplett rein.

**Comment by benderl** [comment]
Mit dem Layout des Status bin ich soweit einverstanden. Müsste noch geprüft werden, wie das dann auf verschiedenen Anzeigen skalieren kann. Das sollte aber das Framework hergeben.

Die "Gesamtladung des Ladepunktes" soll genau was beinhalten? Den aktuellen Zählerstand oder die Energie des laufenden Ladepunktes? Beides würde zumindest von den Daten her zum Ladepunkt gehören und müsste im linken Bereich integriert werden. Rechts sind ausschließlich Daten vom Fahrzeug.

**Comment by Saharel001** [comment]
> Mit dem Layout des Status bin ich soweit einverstanden. Müsste noch geprüft werden, wie das dann auf verschiedenen Anzeigen skalieren kann. Das sollte aber das Framework hergeben.
> 
> Die "Gesamtladung des Ladepunktes" soll genau was beinhalten? Den aktuellen Zählerstand oder die Energie des laufenden Ladepunktes? Beides würde zumindest von den Daten her zum Ladepunkt gehören und müsste im linken Bereich integriert werden. Rechts sind ausschließlich Daten vom Fahrzeug.

Hier geht es darum den Gesamtverbrauch (import) des LP im Display sehen zu können.

**Comment by benderl** [comment]
Also den Zählerstand? Was ist hier der Anwendungsfall? Die geladene Energie für diesen Ladevorgang ist mir ja noch plausibel.

**Comment by Saharel001** [comment]
> Also den Zählerstand? Was ist hier der Anwendungsfall? Die geladene Energie für diesen Ladevorgang ist mir ja noch plausibel.

In vielen Unternehmen ist die Abrechnung über Fotos vom Zählerstand möglich. Vor der Ladung und am Ende je ein Bild.
Für mich als Besitzer irrelevant da ich das Ladeprotokoll habe, wenn ich aber Besuch habe und dieser möchte Laden und die Kosten bei seinem AG abrechnen, dann schon.

Wenn das zu speziell ist, kein Thema Im Forum gibt es dazu aber auch anfragen.

**Comment by benderl** [comment]
Ich würde es vorerst zurückstellen.

**Comment by Saharel001** [comment]
Alle klar, habe nur die Statusview mal als draft PR gemacht. https://github.com/openWB/core/pull/1217
