### ISSUE TITLE
ModbusTCP Register 10160 RFID Fehler

### ISSUE THREAD

**Issue by atze09** [openWB/core#1224]
Hallo,

Ich habe eine Problem mit dem RFID Register des Modbus TCP.
Alle anderen Register erreiche ich via Windows Modbus Master. Jedoch bei 10160 und den folgenden bekomme ich einen Fehler.
![Unbenannt](https://github.com/openWB/core/assets/6229866/e445faa7-c289-4b57-8f7b-5878755d42d2)

**Comment by LKuemmel** [comment]
Ich kenne das Programm nicht... Muss bei Start Address nicht die 10160 eingetragen werden?

**Comment by atze09** [comment]
![image](https://github.com/openWB/core/assets/6229866/cb95e819-4170-4461-8a92-34317a9210cc)
Stimmt das hatte ich

> Ich kenne das Programm nicht... Muss bei Start Address nicht die 10160 eingetragen werden?

![image](https://github.com/openWB/core/assets/6229866/a48b4ff9-4da4-4dd4-b82e-e08f2f51e495)

Stimmt das hatte ich eigentlich auch drin, hier nochmal der richtige Screenshot mit gleichem Fehler.
Ich habe es nur Parallel mit dem Programm probiert, da EVCC auch einen Fehler bei der Verbindung auswirft. Wollte wissen, ob der Fehler aufseiten EVCC oder openwb liegt.
Scheinbar passt hier was seitens openwb nicht?
Betrifft auch nur dieses Register alle anderen sind verfügbar.
Echt komisch

**Comment by LKuemmel** [comment]
Hast Du einen Tag gescannt?

**Comment by atze09** [comment]
Nein ich habe keinen RFID reader.

**Comment by benderl** [comment]
Bitte mit dem aktuellen Master testen. Es gab einen Fix für nicht vorhandene RFID Tags.
