### ISSUE TITLE
PSA SoC not updating after target SOC reached

### ISSUE THREAD

**Issue by andlem74** [openWB/core#1234]
Affected version: Beta 2023-10-30
Initial PSA SoC query from PSA server works fine. After charging completes with target SoC reached, vehicle was disconnected and reconnected with low SoC (17%). However, in PV mode SoC is not updated from PSA server. Instead, SoC is stuck at calculated value that was reached before disconnect.

**Comment by benderl** [comment]
Please do not fill in issues about beta versions. Development is active in master and feature branches.
This was already addessed in current master branch.
