### ISSUE TITLE
SOC is reset after internet reconnection

### ISSUE THREAD

**Issue by DerHerrW** [openWB/core#1244]
this was an issue in 1.9 before (had been fixed) and I see this in 2.1 again: The SOC is reset to the manually entered value after DSL has been disconnected and reconnected. 
Probably after reconnection the value from the web.openwb.de cloud is read and rewritten.
![Screenshot_20231108_080535](https://github.com/openWB/core/assets/129861137/8b54e0e7-3a91-46d1-ab39-3b6eb968e630)
![Screenshot_20231108_080601](https://github.com/openWB/core/assets/129861137/cecd06ff-07bf-45e2-a55a-4c9f31161fae)

**Comment by benderl** [comment]
Please do not create a new issue for every personal problem. Open a discussion on our forum to distinguish between persenal and general isues.
