### ISSUE TITLE
Extreme Regelschwankungen wenn mehrere Fahrzeuge laden

### ISSUE THREAD

**Issue by sawbuz** [openWB/core#1605]
Ich habe bei mir vier Wallboxen installiert, die zusammen auf einer Zubringerleitung hängen, laut Elektriker soll diese mit maximal 20kW/30A belastet werden. Dafür habe ich in openWB einen virtuellen Zähler eingerichtet, im Lastmanagement alle Phasen auf 30A begrenzt und in der Struktur diesen allen Wallboxen übergeordnet.

Im Beispiel unten laden die Fahrzeuge:
* F1 EV 3 Phasen PV Laden mit Priorität 
* F2 EV 3 Phasen PV Laden
* F3 Hybrid 1 Phase PV Laden

![ladeschwankungen](https://github.com/openWB/core/assets/109587228/1e3beb89-656d-4b32-b420-ca77980c0d06)

Ich würde erwarten, wenn zwei Fahrzeuge ohne Priorität laden, dass beide konstant mit 15A laden. Wenn alle drei Fahrzeuge laden, wobei F1 Priorität hat würde 16 + 7 + 7A erwarten.
Stattdessen regelt openWB den Ladestrom der Fahrzeuge wild hoch und runter, vor allem wenn alle 3 Fahrzeuge laden.

Auch wenn alle Fahrzeuge auf PV-Regelung eingestellt sind würde ausschließen, dass es damit zusammenhängt, man sieht einen deutlichen Unterschied wenn die Ladung durch die PV Leistung begrenzt ist, z.B. ca. 10:53/11:42 im Diagramm.
Wenn im Diagramm ein Fahrzeug dazukommt/wegfällt, wurde Laden über das Fahrzeug selbst (de)aktiviert bzw. ein/ausgesteckt, nicht durch openWB.

Meine Vermutung ist, dass openWB beim Regeln nur jedes Fahrzeug einzeln betrachtet:
1. Regelintervall 1: es ist genug Strom verfügbar, Fahrzeug auf 16A setzen (für alle Fahrzeuge einzeln)
2. Regelintervall 2: maximaler Zählerstrom ist überschritten, da alle Fahrzeuge mit 16A laden, Fahrzeug auf einen niedrigeren Strom setzen (für alle Fahrzeuge einzeln)
3. zurück zu Schritt 1

**Comment by LKuemmel** [comment]
Für individuelle Probleme bitte das Forum oder die Ticketfunktion benutzen. https://forum.openwb.de/viewtopic.php?t=1526

Das Lastmanagement berücksichtigt alle Fahrzeuge. Ohne Logs ist es nicht möglich, herauszufinden, warum die Regelung bei Dir schwingt.
