### ISSUE TITLE
Geräte mit mehreren Zählertypen (Fronius)

### ISSUE THREAD

**Issue by vuffiraa72** [openWB/core#230]
Bisher habe ich gesehen, dass es nur beim Fronius WR unterschiedliche Zählertypen gibt: `counter_s0` und `counter_sm`.
Bei anderen Geräten wird der Zähler immer als Typ `counter` definiert.

In der weiteren Logik wird damit unterschiedlich umgegangen, einmal wird geprüft, ob im Typ das Wort `counter` enthalten ist, aber es wird auch nur auf `counter` geprüft. Dadurch kann man zwar einen Fronius -Zähler konfigurieren, aber er taucht dann nicht auf der Einstiegsseite auf und wird auch nicht beim Status ausgeführt. In der Konfiguration ist er aber vorhanden und es werden Daten abgefragt

Weitere Sonderfälle sind eventuell `cp_counter` und `evu_counter`.

Die Frage ist also, soll es unterschiedliche Typenbezeichnungen geben, oder müssen Geräte mit mehreren Zählern, WRs und Speichern umgehen können, wenn die sich nicht direkt am Gerätetyp unterscheiden lassen?

**Comment by hhoefling** [comment]
Ich  bin kein python Spezialist. Aber sollte man nicht prüfen ob was von der basisklasse Counter abgeleitet ist statt eines textvergleiches

**Comment by LKuemmel** [comment]
Das Issue ist schon eine Weile offen... wir waren nicht untätig, sondern haben verschiedene Lösungsansätze durchdacht. Allerdings war keiner der Lösungsansätze trivial, sodass es erstmal einen Workaround für das Fronius-Modul gibt.

**Comment by LKuemmel** [comment]
@hhoefling Ja, innerhalb des Devices wird mit `isinstance` geprüft, ob von der entsprechenden Counterklasse abgeleitet wurde.
Dies ist jedoch nicht an allen Stellen möglich, da zB das Frontend gar nicht mit Instanzen arbeitet.
