### ISSUE TITLE
MQTT-PV-WR-Werte: Unterschiedliche Topics in Doku und Code

### ISSUE THREAD

**Issue by gvzdus** [openWB/core#278]
Beim Einrichten eines MQTT-Wechselrichters heisst es in der Beschreibung:

openWB/set/pv/1/power
PV-Leistung in Watt, ohne Nachkommastellen (Integer), nur negativ!
openWB/set/pv/1/counter
Erzeugte Energie in Wh, mit Nachkommastellen (Float), nur positiv

Erwartet werden stattdessen die Topics openWB/set/pv/1/**get**/power und openWB/set/pv/1/**get**/counter

Die Hinweisseite sollte korrigiert werden, allerdings ist im Repository nur generierter Code (web/settings/js/3.js)

**Comment by benderl** [comment]
Der Quellcode ist dort zu finden: https://github.com/openWB/openwb-ui-settings

Ich passe die Beschreibung der Topics noch an.

**Comment by benderl** [comment]
Ist im Repo openwb-ui-settings angepasst. Kommt beim nächsten Build also hier mit rein.
