### ISSUE TITLE
SoC Modul kann nicht gespeichert werden

### ISSUE THREAD

**Issue by MartinRinas** [openWB/core#368]
@LKuemmel ich habe leider nach wie vor Probleme mit dem Speichern der SoC Module in der Fahrzeugkonfiguration. Zum klappt bei neu angelegten Fahrzeugen die Karte nach wie vor nicht aus, soc_module/config wird fürs neue Fahrzeug nicht angelegt. Zudem wird das neu angelegte Fahrzeug nicht sofort angezeigt sondern die Seite muss neu geladen werden.

Wenn ich dieses Topic mit einem leeren Array anlege klappt die Kachel auf und ich kann ein SoC Modul auswählen, allerdings schlägt speichern fehl, im UI verschwindet das ausgewählte Modul auch wieder.

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/29856849/162066652-734cfdfd-4445-4a7e-8cc0-cb431750c434.png">

vue konsolen log: 
[192.168.178.99-1649277205494.log](https://github.com/openWB/core/files/8430386/192.168.178.99-1649277205494.log)

**Comment by benderl** [comment]
Ja, das ist derzeit defekt. Wir arbeiten dran.
