### ISSUE TITLE
Daten der Monatsausertung deutlich zu gering

### ISSUE THREAD

**Issue by MartinRinas** [openWB/core#663]
Ich hab' mir eben mal die Monatsauswertung für November angesehen, da stimmt etwas mit dem Graph nicht. Die Monatssummen kommen hin, rd. 300kWh habe ich an einem Ladepunkt bereits geladen.

Allerdings sehe ich diese Energiemengen überhaupt gar nicht im Chart:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/29856849/203159525-2d06aeb8-b1c8-4bad-b0f5-e9fec8f4fcd2.png">

So sieht der Monat im Sunnyportal aus:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/29856849/203159659-cc2dd82c-5dd5-4065-8d7f-267a1816b157.png">

Andere Monate sind ähnlich falsch, im Oktober geht die Skala gleich nur bis 2,8kWh:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/29856849/203159851-d486d06c-e498-4c93-a147-de1df6b369fc.png">

Kann euch gern die Rohdaten, CSVs oder Logs liefern wenn etwas benötigt wird.

**Comment by MartinRinas** [comment]
Ja, die Zählerstände sind korrekt, eben mal den EVU Zähler mit den Daten aus dem Sunnyportal abgeglichen, das stimmt gut. Die Daten im Broker sind auch korrekt und identisch mit denen aus dem CSV. Auffällig ist lediglich dass ich ein paar Einträge für den 1. November habe. Ich hab' die Daten mal in Excel gezogen und den Tagesimport für Zähler 7 (EVU) ausgerechnet:
![image](https://user-images.githubusercontent.com/29856849/203378969-2179b0d3-7b82-4716-bb01-90d921a021e2.png)

**Comment by benderl** [comment]
Kannst Du die JSON Datei bitte mal anhängen?

**Comment by MartinRinas** [comment]
ja klar. (Musste die Dateien in .txt umbenennen, GitHub mag wohl keine .json Dateien)
[202211.json.txt](https://github.com/openWB/core/files/10071032/202211.json.txt)

[202210.json.txt](https://github.com/openWB/core/files/10071031/202210.json.txt)

**Comment by benderl** [comment]
Mit PR #666 sollte die Darstellung jetzt passen.

**Comment by MartinRinas** [comment]
ja in der Tat, danke @benderl, passt jetzt. 
![image](https://user-images.githubusercontent.com/29856849/203504650-14ce164f-175c-4b9d-8fef-056c018004b8.png)
