### ISSUE TITLE
GitHub Desktop kann nicht mehr Clonen

### ISSUE THREAD

**Issue by hhoefling** [openWB/core#833]
```
Tutorial: Erstkonfiguration.md
Tutorial: Konfiguration Geräte und Komponenten.md
```
Seit die beiden Tutorial-Dateien im DOCS Zweig sind kann man das Repro nicht mehr
mit GitHub Desktop clonen.
Github Desktop stolper über den ":" im Namen .
Nach Entfernen der Dateien klappt das Clonen mit GitHub Desktop wieder.
(Probiert in eigenem Fork)

**Comment by benderl** [comment]
Windows?

**Comment by hhoefling** [comment]
Jup.

**Comment by DetMoerk** [comment]
Ist bei mir auch so. Habe auch Github Desktop. Warte dann einfach auf den PR

**Comment by DetMoerk** [comment]
@LKuemmel :Funktioniert im master wieder. für die angelegten Feature Branches müsste man das auch noch nachziehen

**Comment by hhoefling** [comment]
Ok. Löschen ist auch ein Weg.
Aber einfach nur den ":" aus dem Namen nehmen hätte es auch getan..
( oder falls umbennen nicht geht, per Cut&Past in eine neue Seite verpflanzen.)

**Comment by benderl** [comment]
> @LKuemmel :Funktioniert im master wieder. für die angelegten Feature Branches müsste man das auch noch nachziehen

Rebase der Branches schiebe ich nach, wenn der PR #836 gemerged wurde. Eigentlich kann der master noch nicht funktionieren. ;-)

**Comment by benderl** [comment]
Bitte testen, PR ist im master.
