### ISSUE TITLE
Sungrow implementation not working

### ISSUE THREAD

**Issue by seaspotter** [openWB/core#977]
Since beginning of June Sungrow implementation is not working due to two untested and unverified commits in openWB core (2.0) and 1.9 nightly software. 
Several tests were carried out without success of fixing this. Several remarks were made.

Bugfix for this issue is also pretty easy, delete this 2 commits and bring back the old implementation of version 1.9.300 stable then Sungrow will run again.

Commits: https://github.com/openWB/core/commit/21384e34d5785e24e98fcc506cfef8e00ee9e093
https://github.com/openWB/core/commit/e4f753fa9195af1318a8fc550d78e0cfaadb2a84

Reference to forum:

https://openwb.de/forum/viewtopic.php?p=87703#p87703
https://openwb.de/forum/viewtopic.php?p=87694#p87694
https://openwb.de/forum/viewtopic.php?p=87707#p87707

The author of the changes is also not responding on this issue and as already discussed here, he seems even not capable of proper testing of PRs https://openwb.de/forum/viewtopic.php?t=6920&start=20

**Comment by LKuemmel** [comment]
after some additional bugfixes no more bugs were reported
