### ISSUE TITLE
Lastmanagement mit PV-Anlage

### ISSUE THREAD

**Issue by Bascht74** [openWB/core#998]
Kann die Seite Lastmanagement bitte noch mit einem weiteren Beispiel mit PV-Anlage (und ggf. Speicher) erweitert werden?

Es geht um folgende Seite:
https://github.com/openWB/core/wiki/Lastmanagement-und-kaskadierte-Z%C3%A4hler

Aktuell abe ich meine PV-Anlage so konfiguriert: 
![image](https://github.com/openWB/core/assets/66269310/ee49ea82-8085-48c7-9c00-0cebc5398ea9)

Ich bin mir aber nicht sicher, ob das so richtig ist und ich die PV-Anlage an der richtigen Stelle in der Struktur eingeklinkt habe.

Gruß und besten Dank für einen Tipp oder eine Aktualisierung der Seite (werden sicher noch mehr Personen mit dieser Frage existieren).

**Comment by MartinRinas** [comment]
An welcher Stelle soll denn wie begrenzt werden? In deinem Setup werden die beiden Ladepunkte gemeinsam auf 22kW/32A begrenzt. Z.b. weil es sich um eine gemeinsame Zuleitung mit entsprechender Last handelt. Ob der Strom nun von der PV Anlage oder aus dem Netz kommt spielt keine Rolle, die beiden Ladepunkte dürfen gemeinsam nicht mehr als 22kW/32A abgeben.

Eine Begrenzung des Hausanschlusses wird direkt am 'MQTT-Zähler Strom Hauptzähler' konfiguriert, dem sog. EVU Zähler. Also dem Zähler an oberster Stelle in der Hierachie.

**Comment by benderl** [comment]
Geschlossen, weil keine Rückmeldung mehr kam.
